#!/usr/bin/env bash
# Init script to manage the manage_my_process daemon

# Check for the correct number of arguments
if [ $# -ne 1 ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
fi

ACTION=$1

case "$ACTION" in
    start)
        # Start the process in the background (&)
        ./manage_my_process &
        # Save the PID of the last background process to the pid file
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        # Kill the process using the stored PID
        kill "$(cat /var/run/my_process.pid)"
        # Remove the PID file
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        # Stop first
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        # Then start
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
